#include <ccube.h>
#include <ctools.h>
#include <cheaders.h>

#include <string.h>

extern GLdouble mm[16], pm[16];

void invertperspective()
{
        // This only generates a valid inverse matrix for matrices generated by gluPerspective()
        GLdouble inv[16];
        memset(inv, 0, sizeof(inv));

        inv[0*4+0] = 1.0/pm[0*4+0];
        inv[1*4+1] = 1.0/pm[1*4+1];
        inv[2*4+3] = 1.0/pm[3*4+2];
        inv[3*4+2] = -1.0;
        inv[3*4+3] = pm[2*4+2]/pm[3*4+2];

        glLoadMatrixd(inv);
}

